apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: vertx-hello
  name: vertx-hello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: vertx-hello
    spec:
      containers:
      - image: vertex-hello
        imagePullPolicy: Never
        name: vertx-hello
        ports:
        - containerPort: 3001
      restartPolicy: Always
